FROM node:18-alpine as build

WORKDIR /app

COPY . .

RUN ls -al

ARG VITE_API_URL 
ENV VITE_API_URL=$VITE_API_URL

RUN npm install
RUN npm run build

ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
