version: '3.8'
name: test
services:
  client:
    build:
        context: .
        dockerfile: ./client/Dockerfile-client
        args:
          - VITE_API_URL=$VITE_API_URL
    container_name: test-client
    restart: unless-stopped
    ports:
      - "8080:80"

  mysql:
    image: mysql:8.0.29
    container_name: test-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - test-network

  backend:
    build:
      context: ./
      dockerfile: ./server/Dockerfile-server
    container_name: test-server
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    command: npm run start
    networks:
      - test-network

networks:
  test-network: