version: '3.8'

name: nginx-test
services:
  nginx:
    container_name: nginx-nginx
    build:
      context: .
      dockerfile: client/Dockerfile-client
    image: nginx:latest
    ports:
      - "8080:80"
    # volumes:
    #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    # environment:
    #   - CLIENT_URL=${CLIENT_URL}
    #   - SERVER_URL=${SERVER_URL}

  server:
    container_name: nginx-server
    build:
      context: .
      dockerfile: server/Dockerfile-server
    ports:
      - "8000:8000"
    restart: unless-stopped
    command: npm run start
    depends_on:
      - mysql
    networks:
      - test-network

  mysql:
    image: mysql:8.0.29
    container_name: nginx-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - test-network

networks:
  test-network: