version: '3.8'

name: nginx-boilerplate
services:
  nginx:
    container_name: nginx-proxy
    image: nginx:alpine
    ports:
        - "8080:8080"
    restart: unless-stopped
    volumes:
        - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    
  client:
    container_name: nginx-client
    build:
      context: ./client
      dockerfile: Dockerfile-client
      args:
        - VITE_API_URL=$VITE_API_URL
    ports:
      - "3000:3000"

  server:
    container_name: nginx-server
    build:
      context: .
      dockerfile: server/Dockerfile-server
    ports:
      - "8000:8000"
    restart: unless-stopped
    command: npm run start
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.29
    container_name: nginx-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3306:3306'
