# Node.js 버전 18이 설치된 Alpine Linux 기반의 Docker 이미지
# 알파인 리눅스는 '작고', '보안이 뛰어나고', '간단함'. (기본적으로 타 리눅스 배포판보다 훨씬 가볍고 깔끔한 것이 장점)
FROM node:18-alpine

WORKDIR /app
# 현재 디렉토리의 모든 파일과 폴더를 /app 디렉토리로 복사. 
# Docker 이미지 안에서 /app 경로에 프로젝트 파일들이 복사됨.
COPY server .

# ADD 명령어와 마찬가지로 COPY 명령어도 파일 및 폴더를 복사. 단순한 파일 복사 작업을 수행할 때는 COPY가 더 권장됨.
# ADD 명령어 : 압축 해제한 상태로 저장 및 URL 다운로드와 같은 기능 제공

# 작업 디렉토리를 /app로 설정하여 이후의 명령들이 이 디렉토리에서 실행되도록 함.


# 디렉토리 안의 파일 및 폴더 목록을 출력 (Docker 빌드 중에 디렉토리 안의 내용을 확인 가능)
RUN ls /app -al

# /app 디렉토리 안에서 yarn 명령을 실행하여 종속성을 설치한 다음, yarn build api 명령을 실행하여 API를 빌드
RUN npm i && npm run build

EXPOSE 3000

# 컨테이너가 실행될 때 실행될 기본 명령
# RUN npm run start


# package.json을 참조하면 "start:prod": "node dist/apps/api/main", 해당 부분이 있는데

